_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "https://dl.fbaipublicfiles.com/convnext/convnext_base_1k_224_ema.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
#    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_FEATURES: ["res5"]
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 15
  BACKBONE:
    NAME: "convnext_base"

SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 3
  BASE_LR: 0.00025

DATALOADER:
  NUM_WORKERS: 2

