_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "/home/uzair.khattak/CV703/detectron_project/convnext_base_1k_224_ema.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 15
  BACKBONE:
    NAME: "convnext_base"

SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025

DATALOADER:
  NUM_WORKERS: 2

INPUT:
  FORMAT: "RGB"
