_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "/home/uzair.khattak/CV703/detectron_project/convnext_base_1k_224_ema.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    NAME: "build_convnext_fpn_backbone"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 15
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025

INPUT:
  FORMAT: "RGB"

DATALOADER:
  NUM_WORKERS: 2

OUTPUT_DIR: "convnext_B_FPN_1k_weights"