_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 15
  ROI_BOX_HEAD:
    USE_FOCAL_LOSS: 'FOCAL_STAR'
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
DATALOADER:
  NUM_WORKERS: 2
OUTPUT_DIR: "R101_FPN_1k_weights"