_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 15
  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256], [512], [1024]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.33, 0.5, 1.0, 2.0, 3.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: [ "p2","p2","p3", "p4", "p5", "p6", "p6"]
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
DATALOADER:
  NUM_WORKERS: 2
OUTPUT_DIR: "R101_FPN_1k_weights"